# Generated by Django 3.1.2 on 2021-08-07 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_content', models.TextField()),
                ('event_date', models.CharField(max_length=200)),
                ('club_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
                ('school_events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=200)),
                ('announcement_content', models.TextField()),
                ('club_announcements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club')),
                ('school_announcements', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.school')),
            ],
        ),
    ]
