# Generated by Django 3.1.2 on 2021-08-09 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_announcements_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='club_announcements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
    ]
