# Generated by Django 3.1.2 on 2021-08-09 18:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210809_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcements',
            name='school_announcements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.AlterField(
            model_name='events',
            name='club_events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
        migrations.AlterField(
            model_name='events',
            name='school_events',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
    ]
