# Generated by Django 3.1.2 on 2021-08-19 18:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import register.models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_user_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('passcode', models.CharField(default=register.models.generate_random_passcode, max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='isPresident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isPresident', models.BooleanField(default=False)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200)),
                ('event_content', models.TextField()),
                ('event_date', models.CharField(max_length=200)),
                ('club_events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.club')),
                ('school_events', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.school')),
            ],
        ),
        migrations.AddField(
            model_name='club',
            name='members',
            field=models.ManyToManyField(through='register.isPresident', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='club',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.school'),
        ),
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_title', models.CharField(max_length=200)),
                ('announcement_content', models.TextField()),
                ('club_announcements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.club')),
                ('school_announcements', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.school')),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='register.school'),
        ),
    ]
