# Generated by Django 3.1.2 on 2021-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_club_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ispresident',
            name='isCreater',
            field=models.BooleanField(default=False),
        ),
    ]
