# Generated by Django 3.1.2 on 2021-08-22 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_ispresident_iscreater'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='isPresident',
            new_name='Member',
        ),
    ]
