# Generated by Django 3.1.2 on 2021-08-22 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_auto_20210822_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='isOwner',
            field=models.BooleanField(default=False),
        ),
    ]
